#!/bin/bash

yum install -y git gcc wget openssl-devel readline-devel zlib-devel bzip2
yum install -y epel-release

# nodejs
yum remove nodejs npm
curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install -y nodejs
sudo npm install yarn -g

# sqlite3
wget https://www.sqlite.org/2019/sqlite-autoconf-3280000.tar.gz
tar xvfz sqlite-autoconf-3280000.tar.gz
cd sqlite-autoconf-3280000
./configure --prefix=/usr/local
make
sudo make install
sudo find /usr/ -name sqlite3
/usr/local/bin/sqlite3 
sudo mv /usr/bin/sqlite3 /usr/bin/sqlite3_old
ln -s /usr/local/bin/sqlite3 /usr/bin/sqlite3
export LD_LIBRARY_PATH="/usr/local/lib"

# ruby
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
~/.rbenv/bin/rbenv init
source ~/.bash_profile
rbenv -v
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
~/.rbenv/plugins/ruby-build/install.sh
CONFIGURE_OPTS="--disable-install-rdoc" rbenv install 2.6.5
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
source ~/.bash_profile
rbenv global 2.6.5

# rails
printf "install: --no-document \nupdate:  --no-document\n" >> ~/.gemrc
gem install sqlite3 -- --with-sqlite3-lib=/usr/local/lib
gem install rails -v 6.0.0

# app1
mkdir rails_test
cd rails_test/
rails _6.0.0_ new hello_app
cd hello_app/
bundle exec rails s -b 0.0.0.0

# app2
rails _6.0.0_ new toy_app
